# Generated by Django 6.0.5 on 2026-05-28 03:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(db_index=True, help_text='User ID จาก LINE Platform', max_length=255, unique=True, verbose_name='LINE User ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ชื่อที่แสดง')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='เบอร์โทร')),
                ('address', models.TextField(blank=True, default='', verbose_name='ที่อยู่เริ่มต้น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อสินค้าหลัก เช่น Chateau Margaux', max_length=255, verbose_name='ชื่อสินค้า (อังกฤษ)')),
                ('name_th', models.CharField(blank=True, default='', help_text='ชื่อภาษาไทย เช่น ชาโตว์ มาร์โกซ์', max_length=255, verbose_name='ชื่อสินค้า (ไทย)')),
                ('sku', models.CharField(help_text='รหัสสินค้า', max_length=50, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ราคา (บาท)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดขาย')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='รายชื่ออื่นที่ใช้เรียกสินค้านี้ เช่น ["มาร์โกซ์", "Margaux"]', verbose_name='ชื่อเรียกอื่นๆ')),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_message', models.TextField(help_text='ข้อความต้นฉบับที่ลูกค้าส่งมา', verbose_name='ข้อความดิบจาก LINE')),
                ('ai_parsed_data', models.JSONField(blank=True, default=dict, help_text='JSON ที่ Gemini AI วิเคราะห์ได้', verbose_name='ข้อมูลที่ AI วิเคราะห์')),
                ('shipping_address', models.TextField(blank=True, default='', verbose_name='ที่อยู่จัดส่ง')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคารวม (บาท)')),
                ('status', models.CharField(choices=[('pending', 'รอยืนยัน'), ('confirmed', 'ยืนยันแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], db_index=True, default='pending', max_length=20, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, default='', verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่ง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'ออเดอร์',
                'verbose_name_plural': 'ออเดอร์',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='ชื่อที่ AI วิเคราะห์ได้จากข้อความ', max_length=255, verbose_name='ชื่อสินค้าที่ลูกค้าระบุ')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาต่อหน่วย (บาท)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคารวม (บาท)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='ออเดอร์')),
                ('product', models.ForeignKey(blank=True, help_text='ถ้า fuzzy match ไม่เจอจะเป็น null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้า',
                'verbose_name_plural': 'รายการสินค้า',
            },
        ),
    ]
