# Generated by Django 6.0.5 on 2026-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ลิงก์รูปภาพสินค้า'),
        ),
    ]
